FROM centos:7

# Here you can install some packages required
#   for your application in runtime


# For example, if you need to install some python packages,
#   you can do it this way:

# COPY requirements.txt /tmp
# RUN yum install -y python3-pip
# RUN pip3 install -r /tmp/requirements.txt
